stages:
  feature:
    cmd: python3.8 structureEstimation.py
    deps:
    - structureEstimation.py
    params:
    - feature.cardinality
    - feature.density
    - feature.number_trajectories
    - feature.number_variables
    outs:
    - output/estimateStructure.json
    - output/realStructure.json
  evaluate:
    cmd: python3.8 metricsCalculator.py output/realStructure.json output/estimateStructure.json
    deps:
    - metricsCalculator.py
    - output/realStructure.json
    - output/estimateStructure.json
    metrics:
            - output/metrics.json:
                    cache: false











