stages:
  evaluate_structure:
    foreach:
        - 100    
        - 150
        - 150x2
        - 300
    do:
        cmd: python3.8 structureEstimation.py ${item}
        deps:
        - structureEstimation.py
        params:
        - feature.cardinality
        - feature.density
        - feature.number_variables
        outs:
        - output/${item}/estimateStructure.json
        - output/${item}/realStructure.json
