stages:
  prepare:
    cmd: python main.py StructureEstimationExample.py data/networks_and_trajectories_ternary_data_01_3
    deps:
    - StructureEstimationExample.py
    - data/networks_and_trajectories_ternary_data_01_3
    - main.py
    outs:
    - output/estimateStructure.json
    - output/estimateStructure.png
    - output/realStructure.json
  evaluate:
    cmd: python f1score_calculate.py output/estimateStructure.json output/realStructure.json
      output/f1score.json
    deps:
    - f1score_calculate.py
    - output/estimateStructure.json
    - output/realStructure.json
    metrics:
    - output/f1score.json:
        cache: false
