stages:
  prepare:
    cmd: python3 structureEstimation.py data
    deps:
    - structureEstimation.py
    - data
    - params.yaml
    params:
    - feature.number_trajectories
    - feature.number_nodes
    - feature.path
    outs:
    - output/Structure/realStructure1.json
  evaluate:
    cmd: python3 metricsCalculator.py output/Structure/realStructure1.json output/metrics.json
    deps:
    - metricsCalculator.py
    - params.yaml
    - output/Structure/realStructure1.json
    metrics:
    - output/metrics.json:
        cache: false

