stages:
  evaluate:
    cmd: python main.py StructureEstimationExample.py data/data.json result66.json
    deps:
    - StructureEstimationExample.py
    - data/data.json
    - main.py
    metrics:
    - output/result666.json:
        cache: false
