stages:
  evaluate_structure:
    foreach:
        - 100
        - 150
        - 150x2
        - 300
    do:
        cmd: python structureEstimation.py ${item}
        deps:
        - structureEstimation.py
        params:
        - feature.cardinality
        - feature.density
        - feature.number_variables
        outs:
        - output/${item}/estimateStructure.json
        - output/${item}/realStructure.json
  
  evaluate_metrics:
    foreach:
        - 100
        - 150
        - 150x2
        - 300
    do:
        cmd: python metricsCalculator.py ${item} output/${item}/realStructure.json output/${item}/estimateStructure.json
        deps:
        - metricsCalculator.py
        - output/${item}/realStructure.json
        - output/${item}/estimateStructure.json
        metrics:
            - output/${item}/metrics.json:
                    cache: false
