stages:
  feature:
    cmd: python3.8 structureEstimation.py
    deps:
    - structureEstimation.py
    params:
    - feature.cardinality
    - feature.density
    - feature.number_trajectories
    - feature.number_variables
    outs:
    - output/estimateStructure.json
    - output/realStructure.json
  evaluate:
    cmd: python3.8 metricsCalculator.py output/realStructure.json output/estimateStructure.json
    deps:
    - metricsCalculator.py
    - output/realStructure.json
    - output/estimateStructure.json
    metrics:
            - output/metrics.json:
                    cache: false
    plots:
    - output/Graphs/binary_01.pdf:
            cache: false 
    - output/Graphs/binary_02.pdf:
            cache: false
    - output/Graphs/binary_03.pdf:
            cache: false
    - output/Graphs/ternary_01.pdf:
            cache: false
    - output/Graphs/ternary_02.pdf:
            cache: false
    - output/Graphs/ternary_03.pdf:
            cache: false
    - output/Graphs/ternary_03.pdf:
            cache: false 
    - output/Graphs/quaternary_01.pdf:
            cache: false
    - output/Graphs/quaternary_02.pdf:
            cache: false
    - output/Graphs/quaternary_03.pdf:
            cache: false










