stages:
  prepare:
    cmd: python StructureEstimation.py data
    deps:
    - StructureEstimation.py
    - data
    - params.yaml
    params:
    - feature.number_trajectories
    - feature.number_variables
    outs:
    - output/realStructure1.json
  evaluate:
    cmd: python f1score_calculate.py output/realStructure1.json output/metric.json
    deps:
    - f1score_calculate.py
    - params.yaml
    - output/realStructure1.json
    metrics:
    - output/metric.json:
        cache: false
